### ISSUE TITLE
rename.js能加上可以选择是否添加序号的功能吗？

### ISSUE THREAD

**Issue by Saw1g88** [Keywos/rule#11]
有时重命名后想在节点名称结尾序号之前再统一加上些字符。

**Comment by Keywos** [comment]
在 @zhangpeifu 群 或者  @lanjieguanggao tg群里找我反馈
one 参数能清理 只有一个节点的01 可以达到类似的效果吧？ 
不然重复的名字怎么处理？

**Comment by Saw1g88** [comment]
可以自己外加序号啊，或者大佬可以发我一版不自动添加序号的吗？我用GPT改了很多次都不成功，我自己不会写代码。
